export const COMMITS = {
  GET_ALL: {
    START: 'COMMITS.GET_ALL.START',
    FAIL: 'COMMITS.GET_ALL.FAIL',
    SUCCESS: 'COMMITS.GET_ALL.SUCCESS'
  }
}
export const USER = {
  GET_CURRENT: {
    START: 'USER.GET_CURRENT.START',
    FAIL: 'USER.GET_CURRENT.FAIL',
    SUCCESS: 'USER.GET_CURRENT.SUCCESS'
  }
}
